server:
  port: 8762
eureka:
  instance:
    hostname: eureka2
  client:
    serviceUrl:
      defaultZone: http://root:890610@eureka2:8762/eureka/
security:
  user:
    password: 890610
    name: root
  basic:
    enabled: true
spring:
  application:
    name: eureka2