server:
  port: 8010
spring:
  application:
  #用于指定注册到eurekaserver上的名称
    name: microserver-consumer-movie
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:890610@localhost:8761/eureka/
  instance:
  #表示将自己的IP注册到Eureka Server上 如果是false 表示将微服务所在的操作系统的hostname 注册到eurekaServer上
    prefer-ip-address: true
